version: '3.7'

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: my-dynamodb
    hostname: dynamodb
    restart: always
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data
    ports:
      - "8000:8000"
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
