version: "3.8"
services:

  mongodb:
    image : mongo:4
    container_name: my-mongodb-replica
    hostname: mongodb-replica
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=mytestdb
      - MONGO_REPLICA_SET_NAME=rs0
    volumes:
      - mongodb_replica_data:/data/db
      - ./keyfile:/opt/keyfile/keyfile
    ports:
      - 57017:27017
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: "--bind_ip_all --keyFile /opt/keyfile/keyfile --replSet rs0"
volumes:
  mongodb_replica_data:
